config/routes.rb
Rails.application.routes.draw do
	get "monitoring/index"
  get "dashboard/index"
	resources :students do
    resources :guardians, module: 'students'
    resources :profile_photos, module: 'students'
    resources :addresses, only: [:new, :create, :edit, :update], module: 'students'
    resources :courses, only: [:edit, :update], module: 'students'
    resources :statuses, only: [:edit, :update], module: 'students'
    resources :mobiles, only: [:edit, :update], module: 'students'
    resources :emails, only: [:edit, :update], module: 'students'
    resources :id_numbers, only: [:edit, :update], module: 'students'
    resources :id_cards, only: [:edit, :update], module: 'students'
		get :autocomplete_student_full_name, on: :collection
    match "/info" => "students#info", as: :info, via: [:get], on: :member
    match "/report" => "students#report", via: [:get], on: :collection
    match "/update_options" => "students#update_options", as: :update_options, via: [:get], on: :member
    match "/report" => "students#report", via: [:get], on: :collection
    match "/full_template" => "students#full_template", as: :full_template, via: [:get], on: :collection
    match "/initial_template" => "students#initial_template", as: :initial_template, via: [:get], on: :collection
    match "/export" => "students#export", as: :export, via: [:get], on: :collection
    collection { post :import}
	end
	resources :employees do
		get :autocomplete_employee_full_name, on: :collection
	end
	resources :settings
	resources :reports
  resources :student_imports, only: [:new, :create]
  resources :profile_photos
  resources :courses

  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  
  devise_scope :user do
    authenticated :user do
      root 'students#index', as: :authenticated_root
    end

    unauthenticated do
      root 'monitoring#index', as: :unauthenticated_root
    end
  end
  resources :users do
    resources :passwords, only: [:edit, :update], module: 'users'
  	get :autocomplete_user_full_name, on: :collection
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
end

app/models/student.rb
class Student < User
	
  include Filterable

  belongs_to :course
  belongs_to :year_level
	validates :id_number, :tag_uid, :course_id, :year_level_id, presence: true
	validates :id_number, :tag_uid, uniqueness: true
  validates_length_of :mobile, :is => 10

  scope :by_course, -> (course_id) { where course_id: course_id }
  scope :by_year_level, -> (year_level_id) { where year_level_id: year_level_id }
  scope :by_status, -> (status) { where status: status }

  def course_and_year
    if self.year_level.present?
      "#{course} - #{year_level}"
    else
      "#{course}"
    end
  end

  def age
    if self.birthdate.present?
      ((Date.today - self.birthdate.to_date) / 365).floor
    else
      "N/A"
    end
  end

  # def self.import(file)
  #   CSV.foreach(file.path, headers: true) do |row|
  #     Student.where(id_number: row['id_number'], first_name: row['first_name'], last_name: row['last_name']).first_or_create do |student|
  #       student.course_id = Course.find_by(abbreviation: row['course']).id
  #       student.year_level_id = YearLevel.find_by(name: row['year_level']).id
  #       student.middle_name = row['middle_name']
  #       student.gender = row['gender'].to_s.downcase
  #       student.birthdate = row['birthdate']
  #       student.mobile = row['mobile']
  #       student.tag_uid = row['card_uid']

  #       student.create_address(sitio: row['sitio'], 
  #           barangay: row['barangay'], 
  #           municipality: row['municipality'], 
  #           province: row['province'])
  #     end
  #   end
  # end

  # def open_spreadsheet
  #   case File.extname(file.original_filename)
  #   when ".csv" then Csv.new(file.path, nil, :ignore)
  #   when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  #   when ".xlsx" then Roo::Excelx.new(file.path)
  #   else 
  #     raise "Unknown file type: #{file.original_filename}"
  #   end
  # end

  def self.import(file)
    # case File.extname(file.original_filename)
    # when ".csv" then spreadsheet = Roo::CSV.new(file.path, nil, :ignore)
    # when ".xls" then spreadsheet = Roo::Excel.new(file.path, nil, :ignore)
    # when ".xlsx" then 
    spreadsheet = Roo::Spreadsheet.open(file.path)
    # else 
      # raise "Unknown file type: #{file.original_filename}"
    # end
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      Student.where(id_number: row['ID NUMBER'], first_name: row['FIRST NAME'].upcase, last_name: row['LAST NAME'].upcase).first_or_create! do |s|
      
        s.tag_uid = row['CARD UID']
        s.course_id = Course.find_by(abbreviation: row['COURSE']).id
        s.year_level_id = YearLevel.find_by(name: row['YEAR LEVEL']).id
        s.middle_name = row['MIDDLE NAME']
        s.gender = row['GENDER'].to_s.downcase
        s.birthdate = row['BIRTHDATE']
        s.mobile = row['MOBILE']
        if spreadsheet.last_column > 10
          if (row['MUNICIPALITY'] and row['PROVINCE']).present? 
            Address.create(
              user_id: s.id,
              sitio: row['SITIO'], 
              barangay: row['BARANGAY'], 
              municipality: row['MUNICIPALITY'], 
              province: row['PROVINCE'])
          end
        end
      end
    end
  end
end

app/controllers/students/addresses_controller.rb
module Students
	class AddressesController < ApplicationController
		before_action :authenticate_user!

		def new
			@student = Student.find(params[:student_id])
			@address = @student.build_address
		end

		def create
			@student = Student.find(params[:student_id])
			@address = Address.create!(address_params)
		end

		def edit
			@student = Student.find(params[:student_id])
			@address = @student.address
		end

		def update
			@student = Student.find(params[:student_id])
			@address = Address.find(params[:id])
			@address.update_attributes!(address_params)
		end

		private
			def address_params
				params.require(:address).permit(:user_id, :sitio, :barangay, :municipality, :province)
			end
	end
end

app/controllers/students/courses_controller.rb
module Students
	class CoursesController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(course_params)
		end

		private
			def course_params
				params.require(:student).permit(:course_id, :year_level_id)
			end
	end
end

app/controllers/students/emails_controller.rb
module Students
	class EmailsController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(email_params)
		end

		private
			def email_params
				params.require(:student).permit(:email)
			end
	end
end

app/controllers/students/guardians_controller.rb
module Students
	class GuardiansController < ApplicationController
		before_action :authenticate_user!

		def new
			@student = Student.find(params[:student_id])
			@guardian = GuardianForm.new
		end

		def create
			@student = Student.find(params[:student_id])
			@guardian = GuardianForm.new(guardian_params)
			if @guardian.save
				redirect_to info_student_path(@student), notice: 'Guardian details updated.'
			else
				render :new
			end
		end

		def edit
			@student = Student.find(params[:student_id])
			@guardian = GuardianForm.new("id" => @student.id)
		end

		def update
			@student = Student.find(params[:student_id])
			@guardian = GuardianForm.new(guardian_params.merge("id" => @student.id))
			if @guardian.update
				redirect_to info_student_path(@student), notice: 'Guardian details updated.'
			else
				render :new
			end
		end

		private
			def guardian_params
				params.require(:guardian_form).permit(:student_id, :first_name, :middle_name, :last_name, :mobile, :relation, :house_number, :sitio, :barangay, 
                                      											:municipality, :province)
			end
	end
end

app/controllers/students/id_cards_controller.rb
module Students
	class IdCardsController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(card_params)
		end

		private
			def card_params
				params.require(:student).permit(:tag_uid)
			end
	end
end

app/controllers/students/id_numbers_controller.rb
module Students
	class IdNumbersController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(id_number_params)
		end

		private
			def id_number_params
				params.require(:student).permit(:id_number)
			end
	end
end

app/controllers/students/imports_controller.rb
module Students
  class ImportsController < ApplicationController
    before_action :authenticate_user!
    
    def new
      @student_import = StudentImport.new
    end

    def create
      @student_import = StudentImport.new(params[:student_import])
      if @student_import.save
        redirect_to students_url, notice: "Student records imported successfully."
      else
        render :new
      end
    end
  end
end

app/controllers/students/mobiles_controller.rb
module Students
	class MobilesController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(mobile_params)
		end

		private
			def mobile_params
				params.require(:student).permit(:mobile)
			end
	end
end

app/controllers/students/profile_photos_controller.rb
module Students
	class ProfilePhotosController < ApplicationController
		before_action :authenticate_user!

		def create
			@student = Student.find(params[:student_id])
			unless @student.profile_photo.nil?
				@student.profile_photo.destroy
			end
			@profile_photo = @student.create_profile_photo(profile_photo_params)
			if @profile_photo.save
				redirect_to info_student_path(@student), notice: 'Profile photo updated.'
			else
				redirect_to info_student_path(@student), notice: @profile_photo.errors
			end
		end

		private
			def profile_photo_params
				params.require(:profile_photo).permit(:user_id, :avatar)
			end
	end
end

app/controllers/students/statuses_controller.rb
module Students
	class StatusesController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(status_params)
		end

		private
			def status_params
				params.require(:student).permit(:status)
			end
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
	autocomplete :students, :full_name, full: true

  def autocomplete
    @students = Student.all
    @names = @students.map { |m| m.full_name }
    render json: @names
  end

	def index
		@courses = Course.all
		@year_levels = YearLevel.all
		@course = params[:course_id] if params[:course_id].present?
		@year_level = params[:year_level_id] if params[:year_level_id].present?
    @status = params[:status] if params[:status].present?
		@full_name = params[:full_name]
		if @full_name.present?
      @filtered = Student.sort_by(&:reversed_name).search_by_name(params[:full_name])
      @students = Kaminari.paginate_array(@filtered).page(params[:page]).per(30)
    else
			@filtered = Student.filter(by_course: @course, by_year_level: @year_level, by_status: @status).sort_by(&:reversed_name)
			@students = Kaminari.paginate_array(@filtered).page(params[:page]).per(30)
		end
	end

  def report
    @course = params[:course_id] if params[:course_id].present?
    @year_level = params[:year_level_id] if params[:year_level_id].present?
    @status = params[:status] if params[:status].present?
    @students = Student.filter(by_course: @course, by_year_level: @year_level, by_status: @status).sort_by(&:reversed_name)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = FilteredStudentsPdf.new(@students, @status, @course, @year_level, view_context)
        send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Students.pdf"
      end
    end
  end

  def export
    @course = params[:course_id] if params[:course_id].present?
    @year_level = params[:year_level_id] if params[:year_level_id].present?
    @status = params[:status] if params[:status].present?
    @title = @status.present? ? "List of #{@status} students" : "List of students"
    @filtered_courses = Course.order(:name).select {|c| c.students.filter(by_course: @course, by_status: @status).present?}
    @filtered_year_levels = YearLevel.order(:name).select {|y| y.students.filter(by_year_level: @year_level, by_status: @status).present?}
    @students = Student.filter(by_course: @course, by_year_level: @year_level, by_status: @status).sort_by(&:reversed_name)
    respond_to do |format|
      format.xlsx { render xlsx: "export", disposition: 'inline', filename: @title }
    end
  end

  def import
    begin
      Student.import(params[:file])
      redirect_to students_url, notice: 'Students Imported'
    rescue
      redirect_to students_url, notice: 'Invalid Excel File.'
    end
  end

  def full_template
    respond_to do |format|
      format.xlsx { render xlsx: "full_template", disposition: 'inline', filename: "Student Import Template-1" }
    end
  end

  def initial_template
    respond_to do |format|
      format.xlsx { render xlsx: "initial_template", disposition: 'inline', filename: "Student Import Template-2" }
    end
  end

	def new
    @student = Student.new
    @student.build_address
  end
  
  def create
    @student = Student.new(create_params)
    if @student.save
      redirect_to info_student_path(@student), notice: 'Student registered successfully.'
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(update_params)
      redirect_to info_student_path(@student), notice: 'Student updated successfully.'
    else
      render :edit
    end
  end

  def update_options
    @student = Student.find(params[:id])
  end

	def info
		@student = Student.find(params[:id])
    @student_id = Student.find(params[:id])
	end

	private
		def filtering_params(params)
		  params.slice(:course_id, :year_level_id)
		end

    def create_params
      params.require(:student).permit(:id_number, :course_id, :year_level_id,
                :first_name, :middle_name, :last_name, :role, :status,
                :birthdate, :gender, :mobile, :email, :tag_uid,
                address_attributes: [:sitio, :barangay, :municipality, :province])
    end

    def update_params
      params.require(:student).permit(:id_number, :course_id, :year_level_id,
                :first_name, :middle_name, :last_name,
                :birthdate, :gender, :mobile, :email, :tag_uid)
    end
end

app/views/students/_form.html.erb
<%=simple_form_for @student do |f| %>
  <%=f.error_notification %>
  <%= f.input :role, input_html: { value: User.roles.keys.to_a.first }, as: :hidden %>
  <%= f.input :status, input_html: { value: User.statuses.keys.to_a.first }, as: :hidden %>
  <div class="row">
    <div class="col-md-7">
      <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
          <%= f.input :id_number, label: "ID Number", as: :numeric %>
          <div class="row">
            <div class="col-md-6 col-xs-6">
              <%= f.input :course_id, collection: Course.all.map {|c| [c.abbreviation, c.id]}, prompt: '-- Choose Course --' %>
            </div>
            <div class="col-md-6 col-xs-6">
              <%= f.input :year_level_id, collection: YearLevel.all.map {|c| [c.name, c.id]}, prompt: '-- Choose Year Level --' %>
            </div>
          </div>
          <br>
        </div>
      </div>
      <h4 class="no-bottom-margin">Personal Details</h4>
      <hr class="no-top-margin">
      <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
          <%= f.input :first_name %>
          <%= f.input :middle_name %>
          <%= f.input :last_name %>
          <%= f.input :birthdate, as: :string, input_html: {class: 'datepicker'} %>
          <%= f.input :gender, collection: User.genders.keys.to_a.map{ |g| [g.titleize, g]}, as: :radio_buttons, item_label_class: "radio-inline", item_wrapper_tag: false %>
          <br>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h4 class="no-bottom-margin">Contact Details </h4>
          <hr class="no-top-margin">
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
          <%= f.input :mobile, label: 'Mobile Number', placeholder: 'Enter 11-digit mobile number', as: :numeric %>
          <%= f.input :email, as: :email %>
          <br>
        </div>
      </div>
      <% if @student.new_record? %>
        <div class="row">
          <div class="col-md-12">
            <h4 class="no-bottom-margin">Address Details </h4>
            <hr class="no-top-margin">
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
          </div>
          <div class="col-md-10">
            <%=f.simple_fields_for :address do |a| %>
              <%=a.input :sitio %>
              <%=a.input :barangay %>
              <%=a.input :municipality, input_html: { value: "Lagawe" } %>
              <%=a.input :province, input_html: { value: "Ifugao" } %>
            <% end %>
            <br>
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-12">
          <h4 class="no-bottom-margin">Card ID</h4>
          <hr class="no-top-margin">
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
        <%= f.input :tag_uid, hint: 'Please tap student ID on the RFID scanner', label: false %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <hr>
          <%= link_to "Cancel", @student.new_record? ? students_path : info_student_path(@student), class: 'btn btn-default' %>
          <%=f.submit 'Save', class: "btn btn-primary pull-right" %>
        </div>
      </div>
    </div>
    <div class="col-md-5">
    </div>
  </div>
<% end %>

app/views/students/_show.html.erb
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">
            <div class="profile-wrapper">
              <% if !@student.record_status.nil? %>
                <div class="overlay status-overlay">
                  <h4 class="text-center text-red">
                    <%= @student.record_status %>
                  </h4>
                </div>
              <% end %>
              <% if @student.profile_photo.blank? %>
                  <%=image_tag("default.png", height: 160, width: 160, :class=>"img-square -img-rounded center-block image") %>
              <% else %>
                  <%= image_tag @student.profile_photo.avatar.url, height: 160, width: 160, class: 'img-square img-rounded center-block image'%>
              <% end %>
              <%= simple_form_for ProfilePhoto.new, url: student_profile_photos_path(@student) do |f| %>
                <%= f.input :user_id, input_html: {value: @student.id}, as: :hidden %>
                <%= f.input :avatar, as: :file, label: false, input_html: { class: 'choose-btn center-block' } %>
                <div class="overlay option-overlay">
                  <div class="col-xs-6 text-center">
                    <a href="" title="Update Photo"><span id="browse" class="text-white fa fa-photo fa-lg"></span></a>
                  </div>
                  <div class="col-xs-6 text-center">
                    <%= link_to edit_student_status_path(@student), title: 'Update Status', remote: :true do %>
                      <span class="text-white fa fa-pencil-square-o fa-lg"></span>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="col-md-5">
            <div class="name-wrapper">
              <h4><%=@student.fullname.try(:upcase) %>
                <span>
                  
                </span>
              </h4>
              <h5 class="course-details">
                Course: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= @student.course_and_year %>
                <%= link_to edit_student_course_path(@student), title: 'Update Course/Year level', remote: true do %>
                  <span class="course-link">&nbsp&nbsp&nbsp&nbsp<i class="fa fa-pencil-square-o"></i></span>
                <% end %>
              </h5>
              <h5 class="id-number-details">
                ID Number: &nbsp&nbsp<%= @student.id_number %>
                <%= link_to edit_student_id_number_path(@student), title: 'Update ID Number', remote: true do %>
                  <span class="id-number-link">&nbsp&nbsp&nbsp&nbsp <i class="fa fa-pencil-square-o"></i></span>
                <% end %>
              </h5>
              <h5 class="id-card-details">
                Card UID: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= @student.tag_uid %>
                <%= link_to edit_student_id_card_path(@student), title: 'Update Card Unique-ID', remote: true do %>
                  <span class="id-card-link">&nbsp&nbsp&nbsp&nbsp <i class="fa fa-pencil-square-o"></i></span>
                <% end %>
              </h5>
            </div>
          </div>
          <div class="col-md-5">
            
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div role="tabpanel">
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="<%='active' if current_page? info_student_path %>">
              <%= link_to 'Info', info_student_path %>
            </li>
            <li class="pull-right <%#='active' if current_page? options_student_path %>">
              <%#= link_to 'Options', options_student_path %>
            </li>
          </ul>
        </div>
        
        <div class="tab-content">
          <div id="my-tab-content" class="tab-content">
            <%= render '/students/partials/info' if current_page? info_student_path %>
            <%#= render '/students/partials/options' if current_page? options_student_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
<script type="text/javascript">
  $('#browse').click(function(e) {
    $('#profile_photo_avatar').click();
    e.preventDefault();
    e.stopPropagation();
    $('#profile_photo_avatar').change(function() {
      var val = $('#profile_photo_avatar').val();
      if (val != ''){
        $('#new_profile_photo').submit();
      }
    });
  });
</script>

app/views/students/_update_options.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">
        Guardian Update Options
      </h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6">
          <%= link_to new_student_guardian_path(@student) do %>
            <h4>Change Guardian</h4>
            <p>This option will create a new guardian.</p>
          <% end %>
        </div>
        <div class="col-md-6">
          <%= link_to edit_student_guardian_path(@student) do %>
            <h4>Update Guardian Details</h4>
            <p>This option will only update guardian details.</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%#= link_to 'Cancel', monitoring_project_path(@project), class: 'btn btn-default pull-left' %>
      <%= link_to "Cancel", "#", class: "btn btn-default pull-left", data: {dismiss: "modal"} %>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <div class="card-title">
        <h4>Student Information - Update Form</h4>
      </div>
    </div>
    <div class="card-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="card">
  <div class="card-header">
    <div class="card-title">
    	<div class="row">
        <div class="col-md-3">
          <h4 class="title"> Students </h4>
        </div>
        <div class="col-md-5">
          <%=form_tag students_path, method: :get do %>
            <div class="input-group stylish-input-group" id="product-prefetch">
              <%= autocomplete_field_tag "full_name", params[:full_name], autocomplete_user_full_name_users_path, class: 'form-control', placeholder: 'Search Student' %>
              <span class="input-group-btn">
                <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
                  <i class="fa fa-search"></i>
                <% end %>
              </span>
            </div>
          <% end %>
        </div>
      	<div class="col-md-4">
          <%= form_tag import_students_path, id: 'import-form', multipart: true do %>
            <%= file_field_tag :file, class: 'choose-btn' %>
          <% end %>
          <span class="pull-right">
            <!-- <div class="btn-group">
              <a role="button" class="btn btn-info" id="browse-file">Import(Excel)</a>
              <a tabindex="0" id="details" class="btn btn-warning btn-tips" role="button" data-toggle="popover" data-placement="bottom" data-html="true" data-trigger="focus" title="" data-content='<%#= render "/students/dropdowns/student_templates" %>'>
                <span class="fa fa-info"></span>
              </a>
            </div> -->
            <a role="button" class="btn btn-info" id="browse-file">Import(Excel)</a>
            <%= link_to "New Student", new_student_path, class: "btn btn-primary" %>
          </span>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-12">
          <h4>Filter Options:</h4>
          <%= form_tag students_path, id: 'student-filter-form', method: :get do%>
            <div class="row">
              <div class="col-md-4">
                <%= select_tag :course_id, options_from_collection_for_select(@courses, "id", "name", params[:course_id]), class: 'bottom-margin-10 form-control border-input', id: "course-filter", prompt: "-- Select Course --" %>
              </div>
              <div class="col-md-4">
                <%= select_tag :year_level_id, options_from_collection_for_select(@year_levels, "id", "name", params[:year_level_id]), class: 'bottom-margin-10 form-control border-input', id: "year-level-filter", prompt: "-- Select Year Level --" %>
              </div>
              <div class="col-md-4">
                <%= select_tag :status, options_for_select(whitelisted_statuses, params[:status]), class: ' form-control border-input', id: "status-filter", prompt: "-- Select Status --" %>
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-md-12">
                <%=link_to "Print (PDF)", report_students_path(format: 'pdf', course_id: @course, year_level_id: @year_level, status: @status), class: "btn btn-info active" if @students.present? %>
                <%=link_to "Export (Excel)", export_students_path(format: :xlsx, course_id: @course, year_level_id: @year_level, status: @status), class: "btn btn-info active" if @students.present? %>
                <%= link_to "Reset Filters", students_path, class: 'btn btn-warning pull-right' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <p><%= "#{@filtered.count} result/s found." %></p>
    </div>
  </div>
  <div class="card-body">
  	<table class="table table-hover">
  		<tr>
        <th>ID Number</th>
  			<th>Name</th>
  			<th>Course</th>
        <th>Mobile</th>
  			<th></th>
  		</tr>
  		<% @students.each do |student| %>
  			<tr>
          <td><%= student.id_number %></td>
  				<td>
            <%= student.reversed_name.upcase %>
            <small class="label label-<%= "warning" if student.status == "suspended" %><%= "danger" if student.status == "dropped" %>">
              <%= student.record_status %>
            </small>
          </td>
  				<td><%= student.try(:course).try(:abbreviation) %></td>
          <td><%= student.try(:mobile) || "N/A" %></td>
  				<td>
            <%=link_to "Details", info_student_path(student), class: "btn btn-xs btn-info" %>
            <%#= render '/students/dropdowns/student_options', student: student %>    
          </td>
  			</tr>
  		<% end %>
  	</table>
  	<div class="modal-footer">
      <center><%= paginate @students, :window => 1 %></center>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('#browse-file').click(function(e) {
    $('#file').click();
    e.preventDefault();
    e.stopPropagation();
    $('#file').change(function() {
      var val = $('#file').val();
      if (val != ''){
        $('#import-form').submit();
      }
    });
  });
</script>

<script type="text/javascript">
  $('#course-filter').change(function(e) {
    $('#student-filter-form').submit();
  });
  $('#year-level-filter').change(function(e) {
    $('#student-filter-form').submit();
  });
  $('#status-filter').change(function(e) {
    $('#student-filter-form').submit();
  });
</script>

app/views/students/info.html.erb
<%= render 'show', locals: @student %>

app/views/students/new.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <div class="card-title">
        <h4>Student Information Form</h4>
      </div>
    </div>
    <div class="card-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/students/update_options.js.erb
$("#update-options-modal").html("<%= escape_javascript(render 'update_options') %>")
$("#update-options-modal").modal( {
    backdrop: 'static',
    keyboard: false
})