config/routes.rb
Rails.application.routes.draw do
	get "monitoring/index"
  get "dashboard/index"
	resources :students do
    resources :guardians, module: 'students'
    resources :profile_photos, module: 'students'
    resources :addresses, only: [:new, :create, :edit, :update], module: 'students'
    resources :courses, only: [:edit, :update], module: 'students'
    resources :statuses, only: [:edit, :update], module: 'students'
    resources :mobiles, only: [:edit, :update], module: 'students'
    resources :emails, only: [:edit, :update], module: 'students'
    resources :id_numbers, only: [:edit, :update], module: 'students'
    resources :id_cards, only: [:edit, :update], module: 'students'
		get :autocomplete_student_full_name, on: :collection
    match "/info" => "students#info", as: :info, via: [:get], on: :member
    match "/report" => "students#report", via: [:get], on: :collection
    match "/update_options" => "students#update_options", as: :update_options, via: [:get], on: :member
    match "/report" => "students#report", via: [:get], on: :collection
    match "/full_template" => "students#full_template", as: :full_template, via: [:get], on: :collection
    match "/initial_template" => "students#initial_template", as: :initial_template, via: [:get], on: :collection
    match "/export" => "students#export", as: :export, via: [:get], on: :collection
    collection { post :import}
	end
	resources :employees do
		get :autocomplete_employee_full_name, on: :collection
	end
	resources :settings
	resources :reports
  resources :student_imports, only: [:new, :create]
  resources :profile_photos
  resources :courses

  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  
  devise_scope :user do
    authenticated :user do
      root 'students#index', as: :authenticated_root
    end

    unauthenticated do
      root 'monitoring#index', as: :unauthenticated_root
    end
  end
  resources :users do
    resources :passwords, only: [:edit, :update], module: 'users'
  	get :autocomplete_user_full_name, on: :collection
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord

  include PgSearch
  require 'csv'
  require 'roo'

  pg_search_scope :search_by_name, :against => [:full_name, :first_name, :last_name]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :address, dependent: :destroy
  has_one :relationship, dependent: :destroy
  has_one :guardian, through: :relationship
  has_one :profile_photo, dependent: :destroy

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :profile_photo
  
  enum role:[:student, :employee, :admin, :developer]
  enum status:[:clear, :suspended, :dropped]
  BLACKLISTED_ROLES = ['admin', 'developer']
  WHITELISTED_ROLES = ['student', 'employee']
  BLACKLISTED_STATUS = ['clear']
  enum gender:[:male, :female]
  
  
  validates :first_name, :last_name, :role, presence: true
  
  before_save :set_full_name, :set_join_date
  before_validation :set_role, :set_email_password

  delegate :details, to: :address, prefix: true, allow_nil: true

  def self.whitelisted_roles
    roles.keys - BLACKLISTED_ROLES
  end

  def self.blacklisted_roles
    roles.keys - WHITELISTED_ROLES
  end

  def self.whitelisted_statuses
    statuses.keys - BLACKLISTED_STATUS
  end

  def order_by_reversed_name
    Student.all.sort_by {|s| s.reversed_name}
  end

  def record_status
    if self.clear? || self.status.nil?
      nil
    elsif self.suspended?
      "SUSPENDED"
    elsif self.dropped?
      "DROPPED"
    end
  end

  def self.types
    %w(Employee Student)
  end
  
  def fullname
  	if self.middle_name.present?
    	"#{first_name.upcase} #{middle_name.first.upcase}. #{last_name.upcase}"
    else
    	"#{first_name.upcase} #{last_name.upcase}"
    end
  end

  def name
  	"#{first_name.upcase}"
  end

  def reversed_name
    if self.middle_name.present?
  	  "#{last_name.upcase}, #{first_name.upcase} #{middle_name.first.upcase}."
    else
      "#{last_name.upcase}, #{first_name.upcase}"
    end
  end

  private

  def set_role
    if self.role.nil?
      if self.class.name == "User"
        self.role = "admin"
      elsif self.class.name == "Student"
        self.role = "student"
      elsif self.role == "Employee"
        self.role = "employee"
      end
    end
  end

  def set_email_password
    if self.student?
      generated_password = Devise.friendly_token.first(8)
      if self.email.blank? and self.password.blank?
        if self.last_name.present? and self.first_name.present?
          rand_num = 3.times.map{ SecureRandom.random_number(9)}.join.to_s
          fname_down = self.last_name.downcase
          lname_down = self.first_name.downcase.first
          self.email = "#{fname_down}.#{lname_down}#{rand_num}@ifsu.com"
      		self.password = generated_password
      		self.password_confirmation = generated_password
      	end
      elsif self.email.present? and self.password.blank?
        self.password = generated_password
        self.password_confirmation = generated_password
      end
    end
  end

  def set_join_date
    if self.join_date.nil?
      openning = Openning.first.openning_date
      self.join_date = openning
    end
  end

  def set_full_name
    self.full_name = fullname.upcase
    self.first_name = first_name.upcase
    self.middle_name = middle_name.upcase if middle_name.present?
    self.last_name = last_name.upcase
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	before_action :authenticate_user!
  layout 'signin'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  autocomplete :user, :full_name, full: true

  def autocomplete
    @users = User.all
    @names = @users.map { |m| m.full_name }
    render json: @names
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to settings_url, notice: 'User created successfully.'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      if @user.admin?
        redirect_to destroy_user_session_path, notice: 'User updated successfully. Please relogin.'
      else
        redirect_to info_user_path(@user), notice: 'User updated successfully.'
      end
    else
      render :edit
    end
  end

  def info
    @user = User.find(params[:id])
  end

  def activities
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :mobile, :role, :email, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<%=simple_form_for @user, url: @user.new_record? ? :users : user_path(@user) do |f| %>
  <%=f.error_notification %>
  <div class="row">
    <div class="col-md-4">
      
    </div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-md-6">
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :mobile %>
          <%= f.input :email %>
          <%= f.input :role, input_html: { value: "admin" }, as: :hidden %>
          <hr>
          <% unless @user.new_record? %>
            <p class="text-muted">*Please enter your current password and password confirmation to apply the changes.</p>
            <p class="text-muted">- If you want to change password, type a new one.</p>
          <% end %>
          <%= f.input :password %>
          <%= f.input :password_confirmation %>
        </div>
        <div class="col-md-6">
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <div class="pull-left">
      <%= link_to "Cancel", students_path, class: 'btn btn-default' %>
    </div>
    <%=f.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <div class="row">
            <div class="col-md-2">
            <p></p>
              <% if @user.profile_photo.present? %>
                <%= image_tag @user.profile_photo, height: 100, width: 100, class: "img-rounded center-block"%>
              <% else %>
                <%=image_tag("default.png", height: 100, width: 100, class: "img-rounded center-block") %>
              <% end %>
            </div>
            <div class="col-md-5">
              <h4>
                <br>
                <%=@user.full_name.try(:upcase) %><br />
                <a href="#"><small></small></a>
              </h4>
              <h5>
                <i class="fa fa-list-alt"></i> Role: <%=@user.role.try(:titleize) %>
              </h5>
            </div>
            <div class="col-md-5">
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
      <div class="nav-tabs-navigation">
        <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
          <li class="<%='active' if current_page? info_user_path %>">
            <%= link_to 'Info', info_user_path %>
          </li>
          <!-- <li class="<#%='active' if current_page? activities_user_path %>">
            <%#= link_to 'Activities', activities_user_path %>
          </li> -->
        </ul>
      </div>
      <div class="content">
        <div id="my-tab-content" class="tab-content">
          <%= render '/users/partials/info' if current_page? info_user_path %>
          <%= render '/users/partials/activities' if current_page? activities_user_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/activities.html.erb
<%=render 'show', locals: @activities %>

app/views/users/edit.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <div class="card-title">
        <h4>Update User Details </h4>
      </div>
    </div>
    <div class="card-body">
      <%=render 'form' %>
    </div>
  </div>
</div>

app/views/users/info.html.erb
<%=render 'show' %>

app/views/users/new.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <div class="card-title">
        <h4>User Details</h4>
      </div>
    </div>
    <div class="card-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%=render 'show' %>