config/routes.rb
Rails.application.routes.draw do
	get "monitoring/index"
  get "dashboard/index"
	resources :students do
    resources :guardians, module: 'students'
    resources :profile_photos, module: 'students'
    resources :addresses, only: [:new, :create, :edit, :update], module: 'students'
    resources :courses, only: [:edit, :update], module: 'students'
    resources :statuses, only: [:edit, :update], module: 'students'
    resources :mobiles, only: [:edit, :update], module: 'students'
    resources :emails, only: [:edit, :update], module: 'students'
    resources :id_numbers, only: [:edit, :update], module: 'students'
    resources :id_cards, only: [:edit, :update], module: 'students'
		get :autocomplete_student_full_name, on: :collection
    match "/info" => "students#info", as: :info, via: [:get], on: :member
    match "/report" => "students#report", via: [:get], on: :collection
    match "/update_options" => "students#update_options", as: :update_options, via: [:get], on: :member
    match "/report" => "students#report", via: [:get], on: :collection
    match "/full_template" => "students#full_template", as: :full_template, via: [:get], on: :collection
    match "/initial_template" => "students#initial_template", as: :initial_template, via: [:get], on: :collection
    match "/export" => "students#export", as: :export, via: [:get], on: :collection
    collection { post :import}
	end
	resources :employees do
		get :autocomplete_employee_full_name, on: :collection
	end
	resources :settings
	resources :reports
  resources :student_imports, only: [:new, :create]
  resources :profile_photos
  resources :courses

  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  
  devise_scope :user do
    authenticated :user do
      root 'students#index', as: :authenticated_root
    end

    unauthenticated do
      root 'monitoring#index', as: :unauthenticated_root
    end
  end
  resources :users do
    resources :passwords, only: [:edit, :update], module: 'users'
  	get :autocomplete_user_full_name, on: :collection
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
end

app/models/student.rb
class Student < User
	
  include Filterable

  belongs_to :course
  belongs_to :year_level
	validates :id_number, :tag_uid, :course_id, :year_level_id, presence: true
	validates :id_number, :tag_uid, uniqueness: true
  validates_length_of :mobile, :is => 10

  scope :by_course, -> (course_id) { where course_id: course_id }
  scope :by_year_level, -> (year_level_id) { where year_level_id: year_level_id }
  scope :by_status, -> (status) { where status: status }

  def course_and_year
    if self.year_level.present?
      "#{course} - #{year_level}"
    else
      "#{course}"
    end
  end

  def age
    if self.birthdate.present?
      ((Date.today - self.birthdate.to_date) / 365).floor
    else
      "N/A"
    end
  end

  # def self.import(file)
  #   CSV.foreach(file.path, headers: true) do |row|
  #     Student.where(id_number: row['id_number'], first_name: row['first_name'], last_name: row['last_name']).first_or_create do |student|
  #       student.course_id = Course.find_by(abbreviation: row['course']).id
  #       student.year_level_id = YearLevel.find_by(name: row['year_level']).id
  #       student.middle_name = row['middle_name']
  #       student.gender = row['gender'].to_s.downcase
  #       student.birthdate = row['birthdate']
  #       student.mobile = row['mobile']
  #       student.tag_uid = row['card_uid']

  #       student.create_address(sitio: row['sitio'], 
  #           barangay: row['barangay'], 
  #           municipality: row['municipality'], 
  #           province: row['province'])
  #     end
  #   end
  # end

  # def open_spreadsheet
  #   case File.extname(file.original_filename)
  #   when ".csv" then Csv.new(file.path, nil, :ignore)
  #   when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  #   when ".xlsx" then Roo::Excelx.new(file.path)
  #   else 
  #     raise "Unknown file type: #{file.original_filename}"
  #   end
  # end

  def self.import(file)
    # case File.extname(file.original_filename)
    # when ".csv" then spreadsheet = Roo::CSV.new(file.path, nil, :ignore)
    # when ".xls" then spreadsheet = Roo::Excel.new(file.path, nil, :ignore)
    # when ".xlsx" then 
    spreadsheet = Roo::Spreadsheet.open(file.path)
    # else 
      # raise "Unknown file type: #{file.original_filename}"
    # end
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      Student.where(id_number: row['ID NUMBER'], first_name: row['FIRST NAME'].upcase, last_name: row['LAST NAME'].upcase).first_or_create! do |s|
      
        s.tag_uid = row['CARD UID']
        s.course_id = Course.find_by(abbreviation: row['COURSE']).id
        s.year_level_id = YearLevel.find_by(name: row['YEAR LEVEL']).id
        s.middle_name = row['MIDDLE NAME']
        s.gender = row['GENDER'].to_s.downcase
        s.birthdate = row['BIRTHDATE']
        s.mobile = row['MOBILE']
        if spreadsheet.last_column > 10
          if (row['MUNICIPALITY'] and row['PROVINCE']).present? 
            Address.create(
              user_id: s.id,
              sitio: row['SITIO'], 
              barangay: row['BARANGAY'], 
              municipality: row['MUNICIPALITY'], 
              province: row['PROVINCE'])
          end
        end
      end
    end
  end
end

app/controllers/students/addresses_controller.rb
module Students
	class AddressesController < ApplicationController
		before_action :authenticate_user!

		def new
			@student = Student.find(params[:student_id])
			@address = @student.build_address
		end

		def create
			@student = Student.find(params[:student_id])
			@address = Address.create!(address_params)
		end

		def edit
			@student = Student.find(params[:student_id])
			@address = @student.address
		end

		def update
			@student = Student.find(params[:student_id])
			@address = Address.find(params[:id])
			@address.update_attributes!(address_params)
		end

		private
			def address_params
				params.require(:address).permit(:user_id, :sitio, :barangay, :municipality, :province)
			end
	end
end

app/controllers/students/courses_controller.rb
module Students
	class CoursesController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(course_params)
		end

		private
			def course_params
				params.require(:student).permit(:course_id, :year_level_id)
			end
	end
end

app/controllers/students/emails_controller.rb
module Students
	class EmailsController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(email_params)
		end

		private
			def email_params
				params.require(:student).permit(:email)
			end
	end
end

app/controllers/students/guardians_controller.rb
module Students
	class GuardiansController < ApplicationController
		before_action :authenticate_user!

		def new
			@student = Student.find(params[:student_id])
			@guardian = GuardianForm.new
		end

		def create
			@student = Student.find(params[:student_id])
			@guardian = GuardianForm.new(guardian_params)
			if @guardian.save
				redirect_to info_student_path(@student), notice: 'Guardian details updated.'
			else
				render :new
			end
		end

		def edit
			@student = Student.find(params[:student_id])
			@guardian = GuardianForm.new("id" => @student.id)
		end

		def update
			@student = Student.find(params[:student_id])
			@guardian = GuardianForm.new(guardian_params.merge("id" => @student.id))
			if @guardian.update
				redirect_to info_student_path(@student), notice: 'Guardian details updated.'
			else
				render :new
			end
		end

		private
			def guardian_params
				params.require(:guardian_form).permit(:student_id, :first_name, :middle_name, :last_name, :mobile, :relation, :house_number, :sitio, :barangay, 
                                      											:municipality, :province)
			end
	end
end

app/controllers/students/id_cards_controller.rb
module Students
	class IdCardsController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(card_params)
		end

		private
			def card_params
				params.require(:student).permit(:tag_uid)
			end
	end
end

app/controllers/students/id_numbers_controller.rb
module Students
	class IdNumbersController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(id_number_params)
		end

		private
			def id_number_params
				params.require(:student).permit(:id_number)
			end
	end
end

app/controllers/students/imports_controller.rb
module Students
  class ImportsController < ApplicationController
    before_action :authenticate_user!
    
    def new
      @student_import = StudentImport.new
    end

    def create
      @student_import = StudentImport.new(params[:student_import])
      if @student_import.save
        redirect_to students_url, notice: "Student records imported successfully."
      else
        render :new
      end
    end
  end
end

app/controllers/students/mobiles_controller.rb
module Students
	class MobilesController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(mobile_params)
		end

		private
			def mobile_params
				params.require(:student).permit(:mobile)
			end
	end
end

app/controllers/students/profile_photos_controller.rb
module Students
	class ProfilePhotosController < ApplicationController
		before_action :authenticate_user!

		def create
			@student = Student.find(params[:student_id])
			unless @student.profile_photo.nil?
				@student.profile_photo.destroy
			end
			@profile_photo = @student.create_profile_photo(profile_photo_params)
			if @profile_photo.save
				redirect_to info_student_path(@student), notice: 'Profile photo updated.'
			else
				redirect_to info_student_path(@student), notice: @profile_photo.errors
			end
		end

		private
			def profile_photo_params
				params.require(:profile_photo).permit(:user_id, :avatar)
			end
	end
end

app/controllers/students/statuses_controller.rb
module Students
	class StatusesController < ApplicationController
		before_action :authenticate_user!

		def edit
			@student = Student.find(params[:student_id])
		end

		def update
			@student = Student.find(params[:student_id])
			@student.update!(status_params)
		end

		private
			def status_params
				params.require(:student).permit(:status)
			end
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
	autocomplete :students, :full_name, full: true

  def autocomplete
    @students = Student.all
    @names = @students.map { |m| m.full_name }
    render json: @names
  end

	def index
		@courses = Course.all
		@year_levels = YearLevel.all
		@course = params[:course_id] if params[:course_id].present?
		@year_level = params[:year_level_id] if params[:year_level_id].present?
    @status = params[:status] if params[:status].present?
		@full_name = params[:full_name]
		if @full_name.present?
      @filtered = Student.sort_by(&:reversed_name).search_by_name(params[:full_name])
      @students = Kaminari.paginate_array(@filtered).page(params[:page]).per(30)
    else
			@filtered = Student.filter(by_course: @course, by_year_level: @year_level, by_status: @status).sort_by(&:reversed_name)
			@students = Kaminari.paginate_array(@filtered).page(params[:page]).per(30)
		end
	end

  def report
    @course = params[:course_id] if params[:course_id].present?
    @year_level = params[:year_level_id] if params[:year_level_id].present?
    @status = params[:status] if params[:status].present?
    @students = Student.filter(by_course: @course, by_year_level: @year_level, by_status: @status).sort_by(&:reversed_name)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = FilteredStudentsPdf.new(@students, @status, @course, @year_level, view_context)
        send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Students.pdf"
      end
    end
  end

  def export
    @course = params[:course_id] if params[:course_id].present?
    @year_level = params[:year_level_id] if params[:year_level_id].present?
    @status = params[:status] if params[:status].present?
    @title = @status.present? ? "List of #{@status} students" : "List of students"
    @filtered_courses = Course.order(:name).select {|c| c.students.filter(by_course: @course, by_status: @status).present?}
    @filtered_year_levels = YearLevel.order(:name).select {|y| y.students.filter(by_year_level: @year_level, by_status: @status).present?}
    @students = Student.filter(by_course: @course, by_year_level: @year_level, by_status: @status).sort_by(&:reversed_name)
    respond_to do |format|
      format.xlsx { render xlsx: "export", disposition: 'inline', filename: @title }
    end
  end

  def import
    begin
      Student.import(params[:file])
      redirect_to students_url, notice: 'Students Imported'
    rescue
      redirect_to students_url, notice: 'Invalid Excel File.'
    end
  end

  def full_template
    respond_to do |format|
      format.xlsx { render xlsx: "full_template", disposition: 'inline', filename: "Student Import Template-1" }
    end
  end

  def initial_template
    respond_to do |format|
      format.xlsx { render xlsx: "initial_template", disposition: 'inline', filename: "Student Import Template-2" }
    end
  end

	def new
    @student = Student.new
    @student.build_address
  end
  
  def create
    @student = Student.new(create_params)
    if @student.save
      redirect_to info_student_path(@student), notice: 'Student registered successfully.'
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(update_params)
      redirect_to info_student_path(@student), notice: 'Student updated successfully.'
    else
      render :edit
    end
  end

  def update_options
    @student = Student.find(params[:id])
  end

	def info
		@student = Student.find(params[:id])
    @student_id = Student.find(params[:id])
	end

	private
		def filtering_params(params)
		  params.slice(:course_id, :year_level_id)
		end

    def create_params
      params.require(:student).permit(:id_number, :course_id, :year_level_id,
                :first_name, :middle_name, :last_name, :role, :status,
                :birthdate, :gender, :mobile, :email, :tag_uid,
                address_attributes: [:sitio, :barangay, :municipality, :province])
    end

    def update_params
      params.require(:student).permit(:id_number, :course_id, :year_level_id,
                :first_name, :middle_name, :last_name,
                :birthdate, :gender, :mobile, :email, :tag_uid)
    end
end

app/views/students/partials/_info.html.erb
<div class="tab-pane fade <%='in active' if current_page? info_student_path %>">
  <div class="row">
    <div class="col-md-5">
      <h4 class="personal-details">
        Personal Details
        <%= link_to edit_student_path(@student), title: 'Update Personal Details' do %>
          <span class="pull-right personal-link"><i class="fa fa-pencil-square-o"></i></span>
        <% end %>
      </h4>
      <table class="table table-striped">
        <tr>
          <td style="width:120px">Gender: </td>
          <td><b><%=@student.try(:gender).try(:capitalize) || "N/A" %></b></td>
        </tr>
        <tr>
          <td style="width:120px">Age: </td>
          <td><b><%=@student.age %></b></td>
        </tr>
        <tr>
          <td style="width:120px">Birthdate: </td>
          <td><b><%=@student.try(:birthdate).try(:strftime, "%B %e, %Y") || "N/A" %></b></td>
        </tr>
      </table>
      <br>
      <table class="table table-striped">
        <tr>
          <td style="width:120px">Contact Number: </td>
          <td class="mobile-details">
            <b><%=@student.mobile || "N/A"%></b>
            <%= link_to edit_student_mobile_path(@student), title: 'Update Mobile Number', remote: true do %>
              <span class="mobile-link">&nbsp&nbsp&nbsp&nbsp <i class="fa fa-pencil-square-o"></i></span>
            <% end %>
          </td>
        </tr>
        <tr>
          <td style="width:120px">Email: </td>
          <td class="email-details">
            <b><%=@student.email || "N/A"%></b>
            <%= link_to edit_student_email_path(@student), title: 'Update Email', remote: true do %>
              <span class="email-link">&nbsp&nbsp&nbsp&nbsp <i class="fa fa-pencil-square-o"></i></span>
            <% end %>
          </td>
        </tr>
      </table>
      <br>
      <h4 class="address-details">
        Address Details
        <% if @student.address.present? %>
          <%= link_to edit_student_address_path(student_id: @student, id: @student.address.id), title: 'Update Address Details', remote: true do %>
            <span class="pull-right address-link"><i class="fa fa-pencil-square-o"></i></span>
          <% end %>
        <% else %>
          <%= link_to new_student_address_path(@student), title: 'Update Address Details', remote: true do %>
            <span class="pull-right address-link"><i class="fa fa-pencil-square-o"></i></span>
          <% end %>
        <% end %>
      </h4>
      <table class="table table-striped">
        <tr>
          <td width="120"></td>
          <td><b><%=@student.address_details || "N/A"%></b></td>
        </tr>
      </table>
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-5">
      <h4 class="guardian-details">
        Guardian Details
        <% if @student.guardian.present? %>
          <%= link_to update_options_student_path(@student), title: 'Update guardian', remote: true do %>
            <span class="pull-right guardian-link"><i class="fa fa-pencil-square-o"></i></span>
          <% end %>
        <% else %>
          <%= link_to new_student_guardian_path(@student), title: 'Update guardian details' do %>
            <span class="pull-right guardian-link"><i class="fa fa-pencil-square-o"></i></span>
          <% end %>
        <% end %>
      </h4>
      <table class="table table-striped">
        <tr>
          <td style="width:120px">Name: </td>
          <td><b><%=@student.guardian || "N/A"%></b></td>
        </tr>
        <tr>
          <td style="width:120px">Relationship: </td>
          <td><b><%=@student.relationship || "N/A"%></b></td>
        </tr>
      </table>
      <br>
      <table class="table table-striped">
        <tr>
          <td style="width:120px">Contact Number: </td>
          <td><b><%=@student.guardian.try(:mobile) || "N/A"%></b></td>
        </tr>
        <tr>
          <td style="width:120px">Address: </td>
          <td><b><%=@student.guardian.try(:address_details) || "N/A"%></b></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/students/partials/_options.html.erb
- set grade level individually. <br>
- set school fees for current semester individually.